### ISSUE TITLE
Changing Number of Steps with Existing Pattern

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#103]
If I write a simple 16 step pattern (e.g. snare backbeat, with notes on steps 5 and 13) then change the number of steps for that round (say double it to 32), I expect the new steps to populate in between my written pattern as newly available divisions at a finer grain. Instead, currently the pattern gets shifted since new divisions are just added on to the end of the cycle. 

For duple number of steps (cycle divided into 2, 4, 8, 16, 32), it would be nice to add some math to fulfill the expected result for adding new divisions by having them positioned between existing note ons, preserving the written pattern musically. Triplet divisions would be nice as well. For all the compound / unorthodox divisions (5,7,11,13,14 etc), the way it is now is probably fine unless you are a music super genius :)

**Comment by simonadcock** [comment]
I've adjusted the algorithm so that if the new number of steps is a multiple of the old number of steps it will keep the note ons in the same musical place, otherwise it will just add or remove steps to the end like before.
