### ISSUE TITLE
Touch - dragging on step does not change velocity or probabilty

### ISSUE THREAD

**Issue by simonadcock** [irllabs/roundaround#11]

**Comment by batchku** [comment]
Tried this on the iPhone 11 and Pixel 1.
UX is bad; very difficult to use on small screen

we need to:
1.  change the range of pixels to prob/vel change 
2. give user immediate feedback with a popup to the side (cuz the user can't see the step under her finger)
3. give user feedback when going beyond the edges of the ranges (e.g. flash the circle border on/off with changes without changing the circle size of opacity)
