### ISSUE TITLE
replace Jitsi based audio chat with networked AFrame

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#111]
Rounds uses Jitsi for in-app chat
SimpleVR uses AFrame audio for in-app chat

Jitsi works poorly and AFrame works well.

The objective is to remove Jitsi from Rounds and add AFrame like SimpleVr.

**Comment by batchku** [comment]
This work is done and currently on rounds.studio
@lazarmitic can you confirm ^ and the branch?

@ryhor13 Your task is to merge ^ branch into master.

**Comment by lazarmitic** [comment]
I added everything on master and deployed to production.

**Comment by lazarmitic** [comment]
Commit link: https://github.com/irllabs/roundaround/commit/7e4d446ddd985b35319671e0522042e3eb306ef2
