### ISSUE TITLE
MVP - Draw Error with Time Offset

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#118]
Changing the time offset value currently redraws over the outermost ring. This is a new bug, was working fine before. Tested in Safari and Chrome iOS and on desktop.

**Comment by batchku** [comment]
https://user-images.githubusercontent.com/518356/129458175-375049aa-698e-4355-a1c2-d050f1ce5c5b.mp4

**Comment by deerwolf** [comment]
Looks good!
