### ISSUE TITLE
MVP - Remove Layer Type Drop Down

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#119]
Remove "Layer type" from instrument panel as we are not working with automation data at this time.

**Comment by batchku** [comment]
![2021-08-14_12-30-18](https://user-images.githubusercontent.com/518356/129458199-33af2ecc-f6e8-4b0c-b42d-5342c8872928.png)

**Comment by deerwolf** [comment]
Removed. Looks good.
