### ISSUE TITLE
Velocity / Probability editor disappears on Desktop

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#121]
When I click and hold a step on desktop the step editor (x/y probability vs velocity controller) appears but then vanishes erratically after I move the value.

**Comment by batchku** [comment]
https://user-images.githubusercontent.com/518356/129458319-93853e17-f163-4dd9-a38d-340801065946.mp4

**Comment by deerwolf** [comment]
This is fixed but may have introduce a new bug. If I click and hold a step the editor opens, but if I release my click before I move the x/y value, the x/y editor freezes and persists such that I cannot close or edit it until I create a new step.
