### ISSUE TITLE
Drag to add / remove notes not working on desktop

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#122]
On iOS if I tap a note to turn it on then continue to hold I can "paint" in more note-ons/offs by dragging my finger across adjacent steps. This does not work on desktop (chrome / safari) but would be nice to carry over this feature and expectation as it is a classic drum machine gesture. It seems I am able to drag one note sometimes but no more. This feature is working on iPad please make the behavior the same on desktop.

**Comment by adriannodew** [comment]
I still couldn't understand about this issue so can you make a detailed explanation with screenshot?

**Comment by batchku** [comment]
In order to understand this issue, please try the app side-by-side on an ipad and then on desktop.

-iPad: create a round, touch a step in your round to turn it on; without taking finger off the screen, drag across other steps in the same layer; they also turn on; same for turning off many steps with one gesture
-Desktop: clicking/dragging to activate/deactivate many steps does not work.

**Comment by batchku** [comment]
This does not work.

When I click and drag from one step to many other steps on iPad, they all turn on.
On Desktop, only the next step turns on and then it does not.


Please follow my instructions:
- Compare the performance side by side on iPad and Desktop; they need to be identical; they are not.

**Comment by batchku** [comment]
@muganwas 
I tried this in a few ways with mixed results:
- on chrome and safari on a laptop running OS X; *it works ok*
- on chrome on iOS / iPhone; *does not work*.  Have you tried it?
- on safara on iOS / iphone; *does not work*. Have you tried it?

Generally, for issues that are heavy UI/UX it is critical that you test with iOS also; iOS is our preferred target; it should be prioritized in testing, even above desktop/mouse/keyboard.

**Comment by batchku** [comment]
This is not working well for me on iPad; seems worse than before.

It seems that for dragging to turn many steps on/off, we have moved from "onEntry" of the circle to "onExit".
What i'm noticing on iPad is that as I drag, it misses some and catches some; so inconsistent.
