### ISSUE TITLE
Add ping pong Delay FX to start of signal chain

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#125]
1. Add a new effect at the start of the FX chain:
https://tonejs.github.io/docs/14.7.77/PingPongDelay.html
2. Add new UI for effect at the top of the right-panel effects; get new icon from @mericda

**Comment by deerwolf** [comment]
Let’s try bringing the echo back a bit more, this is too close to a reverb. I believe you will want to increase the delayTime value.

**Comment by deerwolf** [comment]
This still isn't quite right @adriannodew can you tell me the current `maxDelayTime` `delayTime` values in use?

**Comment by adriannodew** [comment]
delay time is 24t

**Comment by adriannodew** [comment]
original maxDelayTime was 0.7 and delayTime was 24t
I changed a little

**Comment by deerwolf** [comment]
I think this is good for now, much more musical. We will tweak this more later.

**Comment by deerwolf** [comment]
Possibly a better delay object here https://tonejs.github.io/docs/14.7.77/PingPongDelay.html

**Comment by batchku** [comment]
@mericda  to provide icon (ping pong paddle?)

**Comment by deerwolf** [comment]
![image](https://user-images.githubusercontent.com/593435/130639625-4b6c35c6-2de9-4c9b-b0e9-280fdb5d4232.png)
![image](https://user-images.githubusercontent.com/593435/130639674-755f33d1-1c64-4ab6-9abd-295c36910a02.png)

**Comment by deerwolf** [comment]
@adriannodew as discussed at our standup we would like to include the effect below in our FX signal chain, it can go at the top so it is the first effect.

https://tonejs.github.io/docs/14.7.77/PingPongDelay.html

**Comment by deerwolf** [comment]
To reiterate: ping pong is a NEW addition to our original effects chain. You need to recover the old delay and place ping pong as a new effect in position 1. There will be 5 FX in total now.

**Comment by adriannodew** [comment]
go back to original effects and then add another one

**Comment by batchku** [comment]
![2021-08-24_11-59-38](https://user-images.githubusercontent.com/518356/130674450-4ba415ad-556f-4c0c-8814-ac878e680e8d.png)
