### ISSUE TITLE
remove live "Record" sample feature

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#129]
The objective is to hide the "Record" feature from the user; leave all functionality in place but hide the UI.

Hide the "Record" feature of each layer and move it to "staging" server.
![2021-08-14_11-52-38](https://user-images.githubusercontent.com/518356/129457432-17a64c81-9e99-47e5-ae51-0276f442e741.png)

**Comment by deerwolf** [comment]
Removed. Looks good.

**Comment by batchku** [comment]
Make the "cloud upaload" button wider to be full inspector width, like the drop down fields above it
Make sure to center the button label horizentally as well

**Comment by batchku** [comment]
@adriannodew 
I repeat:
`Make the "cloud upaload" button wider to be full inspector width`

That means:
![2021-08-19_11-24-45](https://user-images.githubusercontent.com/518356/130123906-ce11ed2d-faa0-4170-99f5-99da34c29f62.png)
