### ISSUE TITLE
Reduce opacity of other people's rounds in a collabo session

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#130]
![2021-08-14_12-12-04](https://user-images.githubusercontent.com/518356/129457888-6e0efcde-bf98-4f40-bc60-c4c008910b94.png)

**Comment by deerwolf** [comment]
Tested with a variety of colors and this looks nice. I think this is good to go.
![Screen Shot 2021-08-18 at 9 41 24 AM](https://user-images.githubusercontent.com/593435/129938049-c76cf25c-81f5-4c6d-be9d-23addb5f5999.jpg)
