### ISSUE TITLE
Participants in a collab can not hear no steps added to the round by other users

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#159]
Steps:
1. User 1 creates round and adds some steps, shares the link with users 2 and 3 who join
2. Users 2 and 3 join, and add some layers and steps

Expected results
1.  All users always here all steps from all layers in the round

Actual results
1.  All users hear the layers/steps that were in the round when the collab started; new layers and steps are only heard by the users that add them, and not by everyone else

**Comment by batchku** [comment]
@muganwas 
I tried this with Chrome on OS X and Chrome on iOS; does not work.

I still see the same bug; when the iOS client adds steps, they DO show up on OS X visually, but I don't hear them.

**Comment by muganwas** [comment]
> @muganwas I tried this with Chrome on OS X and Chrome on iOS; does not work.
> 
> I still see the same bug; when the iOS client adds steps, they DO show up on OS X visually, but I don't hear them.

I've retested with 3 users and it seems there's a problem with the "host" not hearing ALL(some seem to be coming through) new rounds, the other 2 users seem to be working fine.

**Comment by batchku** [comment]
@muganwas 
Please confirm that when a user adds a layer with the "+" button, the following happens in this order:
1. app creates a new layer LOCALLY
2. app creates UI for that layer locally
3. app communication layer creation with firebase
