### ISSUE TITLE
Setup CI to run Cypress tests

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#166]
Make gates for code quality based on branches

**Acceptance Criteria**

1. A dev cannot merge into stage or master branch on github without `./node_modules/.bin/eslint --ext js,jsx src` passing
2. A dev cannot merge into stage or master branch on github without `cypress run` passing
a. when you merge into stage it runs the tests against the stage branch
b. when you merge into master it runs the test against the prod branch
3. Remove git hooks for pre-push (cypress tests) once done
4. When you merge into stage, it deploys to `https://roundaround-stage.web.app/`
5. When you merge stage into master, it deploys to `https://roundaround-dev.web.app/`

**Comment by choshun** [comment]
**Acceptance Criteria**
- A user cannot merge into stage or master branch on github without `./node_modules/.bin/eslint --ext js,jsx src` passing
- A user cannot merge into stage or master branch on github without `cypress run` passing
- Remove git hooks for pre-push (cypress tests) once done
