### ISSUE TITLE
Default behavior: users can NOT change other users' layers/steps

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#21]
Currently a user can change his layers and steps, and any other users.
Make it so that be default, a user can only affect his own layers/steps.
A toggle in the settings menu, available to the user the created the collaboration will allow a user to "open" access to editing all layers.

**Comment by batchku** [comment]
Just tested this on android and computer: bug persists; both users can change all stepts.

**Comment by simonadcock** [comment]
I can't recreate this, it's possible this happens if loading an old session or round. Could you provide steps to recreate?
