### ISSUE TITLE
Buttons should have "active" state

### ISSUE THREAD

**Issue by mericda** [irllabs/roundaround#226]
All buttons on the toolbar (and ideally rest of the app) should have an active state, which is similar to hover (background color opacity: 0.2). Some examples that we should have active state is: 
* Any primary button that opens up a  hoverable/dropdown container, when that container is active such as Mixer/Instruments+Sounds/Steps/Volume/... 
* (M) Mute / (S) Solo buttons inside Mixer and Volume containers when those features are active. 

![CleanShot 2021-11-19 at 18 26 21@2x](https://user-images.githubusercontent.com/19254822/142711374-1461f183-9160-4640-bf59-a5e434d13d6a.png)

**Comment by batchku** [comment]
The active/hover state for the "+" and "mixer" buttons are different than the rest.
The former is lighter, the latter is darker.

@mericda  is this intended?
