### ISSUE TITLE
I should be able to select a layer by tapping it on Mixer. 

### ISSUE THREAD

**Issue by mericda** [irllabs/roundaround#228]
On mixer, each layer has a hover state as it should be, but clicking to that area doesn't do anything. When I tap on a layer on the Mixer, it should select that layer. When that layer is selected, user should be able to see the active state on the round canvas, and the layer inspector should show the details of that layer.

![CleanShot 2021-11-19 at 18 29 10@2x](https://user-images.githubusercontent.com/19254822/142711723-a16e6c63-bb20-4c49-b1bc-d3dd43f6d7fe.png)

**Comment by mericda** [comment]
I tested this, tapping/clicking Mixer updates the inspector, but it doesn't highlight the round itself on the canvas. Can we fix that as well @muganwas ?

**Comment by muganwas** [comment]
> I tested this, tapping/clicking Mixer updates the inspector, but it doesn't highlight the round itself on the canvas. Can we fix that as well @muganwas ?

This currently seems to be working as intended on my end, but I'll try to run further tests just to make sure.

**Comment by mericda** [comment]
Tried both on Safari and Chrome. Selecting a layer from Mixer doesn't highlight the round.
