### ISSUE TITLE
Don't close the Sound selector/dropdown unless I hit Back button or tap /click outside the window.

### ISSUE THREAD

**Issue by mericda** [irllabs/roundaround#235]
Currently if user selects a sound, we dismiss the Sound selector dropdown window, but I think it'll be helpful for users to be able to listen to different sounds with one click. Ideally, we would have mini "Play" buttons for each sounds to preview them, but at this stage, making the sound window persistent until user clicks (Left arrow on top) or clicks outside the dropdown/modal can be an easy solution. Any thoughts @batchku?

<img width="742" alt="image" src="https://user-images.githubusercontent.com/19254822/143989805-321d6cc9-90fd-4b49-8a15-8328b7d69275.png">

**Comment by mericda** [comment]
@muganwas just tested this. "Sound" works as expected, but "Instrument" also does the same behavior. Can we make only the "Sounds" dropdown persistent? When you change an instrument, you anyway would need to change sound.

**Comment by muganwas** [comment]
@mericda For now both modals are persistent but let's discuss this further in the next standup.
