### ISSUE TITLE
re-implement layer mute/umute with double click/tap

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#24]
- expand "stroke" of layer circle to ~48 pixels or close
- expose parameter for setting the max stroke to constants file
- set max stroke of layer to ~64 pixels (min layer volume 48, max volume is at 64)
- expose parameter for setting the max stroke in constants file
- set default layer volume to 0.8
- expose default layer volume

**Comment by simonadcock** [comment]
Is this feature still desired?
