### ISSUE TITLE
New Effects Side Panel

### ISSUE THREAD

**Issue by muganwas** [irllabs/roundaround#242]
![image](https://user-images.githubusercontent.com/12413798/146390757-73fcd34d-c222-4316-a7eb-576f00a7e416.png)

**Comment by muganwas** [comment]
![Screenshot 2021-12-16 at 17 35 03](https://user-images.githubusercontent.com/12413798/146391431-fe9d517b-25bb-4de3-af21-16b9e43ea1b2.png)

**Comment by muganwas** [comment]
![Screenshot 2021-12-16 at 17 30 49](https://user-images.githubusercontent.com/12413798/146391516-febc0d25-ca24-446e-9d0b-a512b1f171a9.png)

**Comment by mericda** [comment]
@muganwas Can we fix the inner insets/paddings and the size of the icons? 

According to Figma, there should be 8dp padding inside and outside of the toggles, and all icons should be in 16dp. 
<img width="246" alt="CleanShot 2021-12-20 at 09 02 15@2x" src="https://user-images.githubusercontent.com/19254822/146804727-e8bca325-7dfa-4986-bfc2-b60a21620b69.png">

<img width="935" alt="Screen Shot 2021-12-20 at 9 01 58 AM" src="https://user-images.githubusercontent.com/19254822/146804744-cc503595-7fac-4e79-8b4a-e8bc5f8f81b6.png">

**Comment by muganwas** [comment]
> @muganwas Can we fix the inner insets/paddings and the size of the icons?
> 
> According to Figma, there should be 8dp padding inside and outside of the toggles, and all icons should be in 16dp including FX and lock icons etc. <img alt="CleanShot 2021-12-20 at 09 02 15@2x" width="246" src="https://user-images.githubusercontent.com/19254822/146804727-e8bca325-7dfa-4986-bfc2-b60a21620b69.png">
> 
> <img alt="Screen Shot 2021-12-20 at 9 01 58 AM" width="935" src="https://user-images.githubusercontent.com/19254822/146804744-cc503595-7fac-4e79-8b4a-e8bc5f8f81b6.png">

Sure, on it.

**Comment by mericda** [comment]
@muganwas It seems like we've lost the ability to apply effects momentarily when pressing the right side of the switch. The  effects experience should (1) let user apply the effect while pressing the button and (2) let user lock that effect if they want to do it continuously. Would you mind trying the existing experience on prod and make necessary changes?

**Comment by muganwas** [comment]
> @muganwas It seems like we've lost the ability to apply effects momentarily when pressing the right side of the switch. The effects experience should (1) let user apply the effect while pressing the button and (2) let user lock that effect if they want to do it continuously. Would you mind trying the existing experience on prod and make necessary changes?

I'll work on it ASAP
