### ISSUE TITLE
Layer Inspector Mobile: Small icons - No padding btw buttons

### ISSUE THREAD

**Issue by mericda** [irllabs/roundaround#244]
When I use the app on mobile, + and mixer icons get smaller. they shouldn't get smaller. Also, specific to roundaround-stage.web.app, the padding between icons on the layer inspector seems to get removed, they shouldn't. 

![IMG_3646](https://user-images.githubusercontent.com/19254822/147646611-030fa814-60f7-4e0b-a3d4-166154540551.jpg)

**Comment by muganwas** [comment]
Since we have an issue dedicated to the mobile version of the layer inspector, there might not be need to address some of these issues yet. I'll deal with the shrinking icons but I'll leave the spacing for now.

**Comment by muganwas** [comment]
Thought it wasn't necessary to deal with the spacing before doing the mobile version but spacing is wrong on tablet too so I'll go ahead and fix it.
