### ISSUE TITLE
small top card UI improvements

### ISSUE THREAD

**Issue by mericda** [irllabs/roundaround#255]
![CleanShot 2022-01-11 at 14 24 55@2x](https://user-images.githubusercontent.com/19254822/148936267-2c2b5de4-f679-4f68-a7ea-df63d9b58daf.png)

Note: Round name button and the back button should have 8dp or "one-x" space between them. 

![CleanShot 2022-01-11 at 14 28 30@2x](https://user-images.githubusercontent.com/19254822/148936491-6a29da8b-c841-4a5d-bb32-d5e1aed4d55b.png)

![CleanShot 2022-01-11 at 14 33 30@2x](https://user-images.githubusercontent.com/19254822/148936510-e71e1886-0ea6-41a8-840a-d65bd822e8cf.png)

**Comment by muganwas** [comment]
@mericda There's nothing like dp on web, when you say dp, it translates to px in web dev.

**Comment by mericda** [comment]
@muganwas yes, I mean px for web, but I think it'll be great if we can define some set variables for these so that we both communicate and use them, and prevent any misunderstanding. I typically strive for increments of 4 for size of UI elements (with some exceptions)

Here is my proposal for item spacing tokens: 
half-x: 4dp
one-x: 8dp
one-and-a-half-x: 12dp
two-x: 16dp
three-x: 24dp
four-x: 32dp

Does that make sense?

**Comment by muganwas** [comment]
It does 100%, I'll set up the variables within the theme.
