### ISSUE TITLE
collaboration created on android device leads to player avatars with same color

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#30]
1.  start app on android
2. create collaboration, go to collaboration link
3. join collaboration from computer

![image](https://user-images.githubusercontent.com/518356/102915619-f4becd80-4436-11eb-93e9-ca63e2f6f02a.png)

**Comment by simonadcock** [comment]
I can only recreate this by being logged in as the same user on both devices. This is not currently supported although I did create a an issue for it in case it's something we want to handle a bit better (#43).
