### ISSUE TITLE
Pattern Presets

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#34]
User is in a single player session and working with multiple layers with different instruments.
User modifies steps in each layer until a satisfactory "pattern" (arrangement of steps on multiple layers with specified instruments and notes) is found.  User touches "store" and clicks on "1" UIs for "Pattern 1".
User changes some step parameters, and the instruments of a layer and adds an instrument with a set of steps.  Users stores this pattern as "pattern 2".
Now to recall patterns, user touches the "recall" and "1" UI's to "Recall Preset 1".  Same for 2, etc....

When in a collaboration, all of the above applies only to the user's layers, not the collaborators.

**Comment by mericda** [comment]
@batchku If a preset saves all the layer info (step formation, instruments, notes), how does a preset differ from a single player session? It sounds like the same thing. Also, recalling (loading) a preset would override the existing layers (and formation, instrument etc,) on that session etc, correct?
