### ISSUE TITLE
[investigation] Create backlog for touch across complete app UX

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#5]
- Evaluate all existing mouse/keyboard interacations
- create backlog of workitems required to move all UX to touch, targeting tablet

**Comment by simonadcock** [comment]
I've tested on a 2019 iPad, a fairly high-end android phone (Pixel 2XL) and a low-end android tablet. 

The iPad performs well in both Chrome & Safari, the graphics are smooth and the audio plays well.
The high-end android phone performs well in Chrome.
The low-end Android tablet performed acceptably when not interacting with the screen too much. There are probably some pretty easy wins to improve graphics performance across all devices which would of course be most noticeable on low-end devices.

As a side note, when a small device (phone) is held in landscape mode the url bar takes a lot of space so should probably request to go fullscreen. When held in portrait mode the avatars should probably be displayed below the round.

The following issues are universal with touch devices:
- Steps cannot be turned on / off
- Dragging on steps does not change velocity or probability
- New layer button does not work

The following issues are Android only:
- Avatars are not displayed at all

**Comment by batchku** [comment]
Great.  This is related to the decision to move away from ThreeJS and towards native Web UIs to resolve touch.
Going with PixyJS sounds reasonable; I will leave this issue open until @simonadcock  captures the issues are captured in individual github issues.

**Comment by batchku** [comment]
Issues are there!
