### ISSUE TITLE
preset store animation (color change) reveals a polygon not a circle

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#67]
the highlighted/white/fading animation showing storing a preset is showing a polygon instead of a circle

**Comment by simonadcock** [comment]
Could you show an image / video of what you mean?

**Comment by batchku** [comment]
Zooming in further, I see that it is not actually a "polygon" issue, but rather the dotted line stroke looks bad when we are changing the fill color for the animation

-Dotted line strokes mean "unfilled" preset
-When use stores a preset, even before the animation starts, we should set the stroke line to be NOT dotted

Here is a still image of the UI after user stores preset 1, and animation starts:
![image](https://user-images.githubusercontent.com/518356/107908582-3df93e00-6f0b-11eb-90d1-f73a4fb5df64.png)

Here is the zoomed in image:
![image](https://user-images.githubusercontent.com/518356/107908596-45b8e280-6f0b-11eb-913f-b01d6ed54451.png)
