### ISSUE TITLE
Singing in as guest should take me to a new round

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#76]
After i choose to sign in as guest and I put in my name, that should take me directly to a new round.

**Comment by batchku** [comment]
This still does not work reliably.
I see that sometimes it goes there, sometimes it ends up here after I sign in as guest:
![image](https://user-images.githubusercontent.com/518356/109330597-afd95d80-7810-11eb-94d9-85b7043b4e09.png)

**Comment by batchku** [comment]
Just tested across chrome os x and iPad; same results.
Sign-in as guest does NOT take me to a new round.

**Comment by simonadcock** [comment]
If you click "Get started" it will show the signin dialog, then take you to a new round if you're a guest. If you just click the "Signin" button in the header it does not do this by intention.
