### ISSUE TITLE
Recording custom samples for a layer

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#77]
Introduce a 2-state toggle for instruments, above the "Instrument" field in the layer info panel.
States are:
1 Built-in (default)
2 Custom

The "Instrument" and "Sound" fields correspond with (1)
For state 2, the UI is A red-circle-record-button and a dropdown; the drop down has one item by default: "Upload..."

When a state is selected, the UIs that do NOT go with the state are greyed-out/not-selectable.

State 1 works as before.

In state 2:
- User can press the "record" button
- a 3-2-1 countdown starts in the record button
- when count down gets to 0, system starts recording sample
- the amplitude of the audio signal in is visualized as 4 close concentric rings outside the record button, corresponding with amplitudes 25%/50%/75%/100%
- user presses record again to stop
- a new ample is made and assigned to the current layer; steps in this layer now play this sound
- a default name is generated for the recorded sample (use date/time) and added to the drop down
- user can rename sample (choose as-easy-as-possible-UX)
- user can delete a sample (choose as-easy-as-possible-UX)
- user can upload a new sample by selecting "Upload..." from the drop down

**Comment by batchku** [comment]
I'm not able to use this feature.
Testing on iPad in chrome:
- create new round
- add steps to the initial 3 layers
- add new layer, select it
- touch "record"; icon changes to "Ready..." without the record icon and is grey; volume meter shows nothing
- recording never seems to start; i touch "Ready..." again and it goes back to the initial state; no recording made.

**Comment by simonadcock** [comment]
Upgrading to iOS 14.4 fixes this (or switching to Safari). We should maybe display a message if we detect Chrome on iOS < 14.4
