### ISSUE TITLE
Custom sample recording not available on Chrome on iPad

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#81]
https://user-images.githubusercontent.com/518356/109395456-4aa16d00-78e1-11eb-9f7b-004f7b25494a.MOV

![Image from iOS](https://user-images.githubusercontent.com/518356/109395886-9f45e780-78e3-11eb-9a78-459ea2f6a2b9.jpg)

**Comment by simonadcock** [comment]
getUserMedia for browsers other than Safari is only available on iOS 14.3+. We should maybe display a message if we detect a non-compatible version?
