### ISSUE TITLE
Lower velocity steps scale funny with Time Offset 

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#87]
Steps with a velocity value of less than 127 appear to scale their position differently when you change the time offset value for that voice. 

![Screen Shot 2021-03-17 at 4 55 46 PM](https://user-images.githubusercontent.com/593435/111553496-c1dc5b00-8741-11eb-9f20-30c30f48845e.jpg)

![Screen Shot 2021-03-17 at 4 57 18 PM](https://user-images.githubusercontent.com/593435/111553540-db7da280-8741-11eb-85f1-6897c6932f33.jpg)

**Comment by ryhor13** [comment]
fixed!

**Comment by muganwas** [comment]
> This may be the same issue as #86. Solve #86 first and see if this is still a thing.

It's still a thing.
