### ISSUE TITLE
Audio Recording on iOS (Safari)

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#96]
After recording an audio clip in the instrument editor, playback of all audio sounds degraded. 

I can't reproduce this on desktop - recording works fine there, only on my iPad. [In video below, audio goes silent though it can still be heard much quieter and seems just out of the left channel on iPad Pro iOS 14.2, Safari]

https://user-images.githubusercontent.com/593435/112213673-9216d280-8bdb-11eb-92e3-515083246f59.MP4

**Comment by simonadcock** [comment]
Works fine in Chrome, WebAudio is poorly implemented in Safari and I think this may be an artefact of that. I'm not sure what we could do differently in the code, happy to spend more time on this if necessary, but going to pause for now as I think this is going to be a time sink.

**Comment by simonadcock** [comment]
Try using a separate thread?
